### ISSUE TITLE
Sharing objects between processes

### ISSUE THREAD

**Issue by bzurkowski** [sileht/cotyledon#30]
Is it safe to pass complex objects into cotyledon services, e.g. a DB connection?
```python
self.add(probe.MyServiceA, workers=1, args=(objA, objB, dbConn))
self.add(probe.MyServiceB, workers=1, args=(objA, objB, dbConn))
```
What consequences (if any) should I expect?

**Comment by sileht** [comment]
It really depends on the lib/soft and co, but most of the times it's not safe at all because cotyledon use os.fork. Anything that creates file description or mmap will have them shared between all processes, if no cooperation are done between these resources, you're are going into hard to debug trouble.

Anyways, cotyledon should be use to have only Services that creates state/fd/mmap/....
